<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <RootNamespace>OpenTK.Graphics</RootNamespace>
  </PropertyGroup>

  <!-- This article is useful for generating code: -->
  <!-- https://learn.microsoft.com/en-au/visualstudio/msbuild/tutorial-custom-task-code-generation?view=vs-2022 -->

  <ItemGroup>
    <PackageReference Include="OpenTK.Mathematics" Version="4.9.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\OpenTK.Core\OpenTK.Core.csproj" />
  </ItemGroup>
</Project>
