<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
      <TargetFramework>net9.0</TargetFramework>
      <RootNamespace>OpenTK.Windowing.GraphicsLibraryFramework</RootNamespace>
      <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
      <LangVersion>latest</LangVersion>
    </PropertyGroup>
    
    <ItemGroup>
      <ProjectReference Include="..\OpenTK.Windowing.Common\OpenTK.Windowing.Common.csproj" />
      <PackageReference Include="OpenTK.redist.glfw" Version="3.4.0.44" />
    </ItemGroup>
</Project>
